### ISSUE TITLE
Selection Bug

### ISSUE THREAD

**Issue by nmock** [futuretap/InAppSettingsKit#284]
Running on iOS8. When specifying a radio group or multi value group, a selection isn't reflected in the UI or updated in the actual preferences. In the UI, it will just appear gray (as if selected), but won't deselect and show that it has actually been selected (with check mark). General toggles work and are reflected fine. I'm subclassing `IASKAppSettingsViewController`, using the version 2.3.4 of InAppSettingsKit (latest as of now). Let me know if any additional information is needed, or if any additional steps are necessary to complete integration with these elements.

**Comment by futuretap** [comment]
I can't reproduce the problem. Do you mean that a user selection in IASK isn't reflected in the UI?

**Comment by nmock** [comment]
I'm using `Root.inApp.plist`. Here is a gist https://gist.github.com/nmock/ba42fdecbb0a9be31f82. Was able to reproduce in the demo app using the specified replacement. The actual selection isn't reflected in the UI nor the model. Here is a video of the issue: https://docs.google.com/file/d/0B7fMw5fknajKN3ZwWHFhZjhsREpnN3ZmU29SR3RzcWlkVUlz

**Comment by futuretap** [comment]
OK, the issue occurred for PSRadioGroupSpecifier's on the root level. Fixed in the latest version, thanks.

**Comment by nmock** [comment]
Thanks for that fix! However, my issue is still persisting and I cannot seem to track down the issue. I was subclassing `IASKAppSettingsViewController`, but I have just reverted to using the standard view controller (for now) to minimize discrepancies. I still cannot get the selection to take. Any ideas as to what else can be going on? I am only using `Root.inApp.plist` because I don't want to have to maintain a separate file for each device type. I deleted all the other Root*.plist files from the bundle. I pretty much  reproduced what I'm doing in the Demo app, but am still experiencing the issue in the video above.

```
IASKAppSettingsViewController *settingsVC = [[IASKAppSettingsViewController alloc] init];
 [navigationController pushViewController:settingsVC animated:NO];
```

Settings.bundle
```
ls -la Settings.bundle/
total 80
drwxr-xr-x@   9 nathanmock  staff    306 Jan 26 12:45 .
drwxr-xr-x@ 120 nathanmock  staff   4080 Jan 26 12:55 ..
-rwxr-xr-x@   1 nathanmock  staff   2573 Jan 19 03:55 Advanced.plist
-rwxr-xr-x@   1 nathanmock  staff  17789 Jan 19 03:55 Complete.plist
-rwxr-xr-x@   1 nathanmock  staff   4098 Jan 26 10:52 Root.inApp.plist
drwxr-xr-x@   3 nathanmock  staff    102 Jan 19 03:55 de.lproj
drwxr-xr-x@   3 nathanmock  staff    102 Jan 19 03:55 en.lproj
-rwxr-xr-x@   1 nathanmock  staff    965 Jan 19 03:55 fast.png
-rwxr-xr-x@   1 nathanmock  staff    780 Jan 19 03:55 slow.png
```

**Comment by futuretap** [comment]
Please set a breakpoint in `-createSelections` and check if it's called on push.

**Comment by nmock** [comment]
`createSelections` doesn't get triggered when tapping the cell. Thanks for the insight, I tracked down the issue to it not being called because `setFile:` wasn't getting called. I don't have much time to dig into project specifics to suggest a fix right now, but I just explicitly set it in my subclass and `createSelections` gets called.

**Comment by futuretap** [comment]
closing this until there's a reproducible case where it doesn't work.
